kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    conjur.org/container-mode: sidecar
    conjur.org/secrets-refresh-enabled: "true"
    conjur.org/secrets-refresh-interval: 10s
  name: questions-api
  namespace: questions-app
  labels:
    app: questions-app
    app.kubernetes.io/component: questions-app
    app.kubernetes.io/instance: questions-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: questions-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: questions-api
    spec:
      serviceAccountName: questions-sa
      containers:
        - name: questions-api
          image: quay.io/smileyfritz/questions-api:v0.2.2
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef: 
                  name: database-secrets
                  key: database-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: database-secrets
                  key: database-password
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef: 
                  name: database-secrets
                  key: database-name
      initContainers:
      - image: cyberark/secrets-provider-for-k8s
        imagePullPolicy: Always
        name: cyberark-secrets-provider-for-k8s
        env:
          - name: CONJUR_AUTHN_LOGIN
            value: host/questions-app
          - name: CONTAINER_MODE
            value: init
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8S_SECRETS
            value: database-secrets
          - name: SECRETS_DESTINATION
            value: k8s_secrets
        envFrom:
          - configMapRef:
              name: conjur-connect-2
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
