---
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
type: Opaque
data:
  database-name: cXVhcmt1c2RiCg==
stringData:
  conjur-map: |-   
    database-user: secrets/username
    database-password: secrets/password
